FROM node:lts-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .

RUN yarn install

# Maybe better to use ts-node-dev after all
CMD npx nodemon --legacy-watch --exec ts-node --ext ts src/index