FROM node:lts-alpine

WORKDIR /app
COPY package.json .
RUN npm i

COPY tsconfig.json .

# https://github.com/facebook/create-react-app/issues/11897#issuecomment-1007206461
ENV WDS_SOCKET_PORT 0
CMD npm start